[package]
name = "pomodoro"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
dirs = "6.0.0"
eframe = "0.31.0"
egui = "0.31.0"
rodio = "0.20.1"
serde = {version = "1.0.218", features = ["derive"]}
serde_json = "1.0.140"
